apiVersion: v1
kind: ConfigMap
metadata:
  name: docs-nginx-config
  namespace: docs
data:
  default.conf: |
    server {
      listen 8080 default_server;
      server_name _;
      port_in_redirect off;
      access_log /dev/stdout combined;
      error_log /dev/stdout info;
      root /www/;

      error_page 404 /404.html;
      error_page 500 502 503 504 /50x.html;

      add_header X-Content-Type-Options nosniff;

      # Health check endpoint for FortiWeb
      location /healthz/ {
        auth_basic off;
        return 200 'OK';
        add_header Content-Type text/plain;
      }

      # Unrestricted access to landing page
      location / {
        add_header X-Content-Type-Options nosniff;
        if ($request_method = HEAD) {
          return 200;
        }
        try_files $uri $uri/ =404;
      }

      # Authentication for content paths
      location ~ ^/(sase|ot|cloud|secops|lanedge)(.*) {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_set_header Authorization $http_authorization;
        try_files $uri $uri/ =404;
      }

      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
