apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secret.yaml
  # Shared ConfigMaps for nginx with htpasswd auth
  - secops-canada/configmap.yaml
  - ai-canada/configmap.yaml
  - enterprise-protection-canada/configmap.yaml
  # Canada region
  - landing-page-canada/deployment.yaml
  - landing-page-canada/service.yaml
  - secops-canada/deployment.yaml
  - secops-canada/service.yaml
  - ai-canada/deployment.yaml
  - ai-canada/service.yaml
  - enterprise-protection-canada/deployment.yaml
  - enterprise-protection-canada/service.yaml
  # Latam region
  - landing-page-latam/deployment.yaml
  - landing-page-latam/service.yaml
  - secops-latam/deployment.yaml
  - secops-latam/service.yaml
  - ai-latam/deployment.yaml
  - ai-latam/service.yaml
  - enterprise-protection-latam/deployment.yaml
  - enterprise-protection-latam/service.yaml
